name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        
      - 
        name: Starter Docker Yarn Test
        uses: cubetiq/starter-docker-yarn-actions@main
        with:
          run: docker version; echo Node":" $(node --version); echo Yarn":" $(yarn --version)
