name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Starter Docker Yarn Test
        uses: cubetiq/starter-docker-yarn-actions@main
        with:
          run: docker version; node --version; npm --version; npx --version; yarn --version
